In [1]:
import numpy as np

In [6]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
# get dimension
a.ndim

1

In [14]:
b = np.array([[1,2,3,8,9],[4,5,6,0,3]])
b

array([[1, 2, 3, 8, 9],
       [4, 5, 6, 0, 3]])

In [9]:
# get shape
a.shape

(3,)

In [10]:
#get shape
b.shape

(2, 3)

In [11]:
# get type
a.dtype

dtype('int32')

In [16]:
# get item size
a.itemsize

4

In [15]:
#get number of elements
b.size

10

In [17]:
# get specific element[r,c]
print(b[0,3])

8


In [18]:
# get specific row 
print(b[0,:])

[1 2 3 8 9]


In [19]:
#get specific column
print(b[:,1])

[2 5]


In [23]:
#get [startindex:endindex:stepsize]
print(b[0,1:-1:1])

[2 3 8]


In [24]:
# All 0s matrix
print(np.zeros((3,3)))
print('*'*20)

# All 1s matrix
print(np.ones((3,2,2), dtype='int32'))
print('*'*20)

# Any other number
print(np.full((2,3,3), 69, dtype='int32'))
print('*'*20)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
********************
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
********************
[[[69 69 69]
  [69 69 69]
  [69 69 69]]

 [[69 69 69]
  [69 69 69]
  [69 69 69]]]
********************


In [26]:
# Random decimal numbers
print(np.random.rand(5,2))

# Random Integer values
print(np.random.randint(-5,8, size=(3,3)))

# The identity matrix
print(np.identity(4))

[[0.38345278 0.58440008]
 [0.81830271 0.16519224]
 [0.72381549 0.69795138]
 [0.21519747 0.30390329]
 [0.76839266 0.95866161]]
[[ 5  1  6]
 [-3  1  1]
 [ 2 -3 -3]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
