In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
print('a')

a


In [5]:
print(a)

[1 2 3]


In [6]:
a[0]

1

In [7]:
a[2]


3

In [8]:
import time 
import sys

In [9]:
b=range(1000)
print(sys.getsizeof(5),len(b))

28 1000


In [10]:
c=np.arange(1000)
print(c.size*c.itemsize)

4000


In [11]:
size = 100000


In [12]:
L1=range(size)
L2=range(size)

A1=np.arange(size)
A3=np.arange(size)

In [13]:
start = time.time()
result =[(x+y) for x,y in zip(L1,L2)]
result =[(x+y) for x,y in zip(L1,L2)]
print("python list took:",(time.time()-start)*1000)

python list took: 33.9508056640625


In [17]:
start = time.time()
result =A1 + A3
print("python list took:",(time.time()-start)*1000)

NameError: name 'A3' is not defined

In [20]:
a1 = np.array([[1,2],[3,4],[5,6]])
a1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
a1.ndim

2

In [22]:
a.itemsize

4

In [23]:
a.shape

(3,)

In [24]:
a1.shape


(3, 2)

In [25]:
a1.itemsize

4

In [26]:
a2 = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)
a2

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [27]:
a2.itemsize

8

In [28]:
a2.shape


(3, 2)

In [30]:
a3 = np.array([[1,2],[3,4],[5,6]], dtype=np.complex)
a3

C:\Users\wwwde\AppData\Local\Temp\ipykernel_14884\3803103296.py:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a3 = np.array([[1,2],[3,4],[5,6]], dtype=np.complex)


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [34]:
b=np.zeros((3,4));
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [35]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
l=range(5)
l

range(0, 5)

In [37]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [38]:
print('concatenation example')
print(np.char.add(['Hello','hi'],['abc','xyz']))

concatenation example
['Helloabc' 'hixyz']


In [40]:
print(np.char.multiply('hello ',3))

hello hello hello 


In [41]:
print(np.char.center('hello ',20,fillchar = '-'))

-------hello -------


In [43]:
print(np.char.capitalize('hello '))

Hello 


In [44]:
print(np.char.title('hello  how are you doing?'))

Hello  How Are You Doing?
