# NUMPY

In [2]:
import numpy as np

In [4]:
arr1 = np.array([[9.0,8.0,7.0,5.0,9.0],[6.0,5.0,4.0,7.8,6.9]])
print(arr1)

arr2 = np.array([[9.0,8.0,7.0,5.0,9.0,4.0,3.2,7.9],[6.0,5.0,4.0]], dtype =object)
print(arr2)

[[9.  8.  7.  5.  9. ]
 [6.  5.  4.  7.8 6.9]]
[list([9.0, 8.0, 7.0, 5.0, 9.0, 4.0, 3.2, 7.9]) list([6.0, 5.0, 4.0])]


In [5]:
print('Dimension of Array 1-',arr1.ndim)
print('Dimension of Array 2-',arr2.ndim)

print('Shape of Array 1-',arr1.shape)
print('Shape of Array 2-',arr2.shape)

print('Type of Array 1-',arr1.dtype)
print('Type of Array 2-',arr2.dtype)

print('Size ',arr1.itemsize)

print('number of elements ',arr1.size)

Dimension of Array 1- 2
Dimension of Array 2- 1
Shape of Array 1- (2, 5)
Shape of Array 2- (2,)
Type of Array 1- float64
Type of Array 2- object
Size  8
number of elements  10


In [6]:
print(arr1[0, 2])

print(arr1[0, :])

print(arr1[:, 2])

print(arr1[0, 1:-1:2])

7.0
[9. 8. 7. 5. 9.]
[7. 4.]
[8. 5.]


In [7]:
print(np.zeros((2,3)))
print('*'*25)

print(np.ones((4,2,2), dtype='int32'))
print('*'*25)

print(np.full((2,3,2), 99, dtype='int32'))
print('*'*25)

[[0. 0. 0.]
 [0. 0. 0.]]
*************************
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
*************************
[[[99 99]
  [99 99]
  [99 99]]

 [[99 99]
  [99 99]
  [99 99]]]
*************************


In [8]:
print(np.random.rand(4,2))


print(np.random.randint(-4,8, size=(3,3)))


print(np.identity(5))

[[0.9872049  0.32751434]
 [0.76259238 0.11751265]
 [0.04455441 0.0136562 ]
 [0.28692206 0.43706897]]
[[-1  2  0]
 [ 0 -2  3]
 [ 6 -1  4]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
