In [2]:
import pandas as pd
import numpy as np

In [21]:
## 1. Creating a DataFrame.
data = {'name': ['Jay', 'Ron', 'joe', 'Ross'],
        'age': ['5', '10', '7', '6'],
        'score': [9.4, 8.9, 7.2, 9]} 

df = pd.DataFrame(data)

## Parameters ##
## Data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
## index: The index (row labels) of the DataFrame.
## columns: The column labels of the DataFrame.
## dtype
## copy


print(df)

   name age  score
0   Jay   5    9.4
1   Ron  10    8.9
2   joe   7    7.2
3  Ross   6    9.0


In [13]:
df1 = pd.read_csv('C:\college\code\data analysis\MW-Pre-Open-Market-06-Sep-2022.csv')
df1

SYMBOL \n PREV. CLOSE \n IEP  PRICE \n CHNG \n %CHNG \n FINAL PRICE \n  \
0   TATAMOTORS         459.00        462.70    3.70     0.81         462.70   
1         NTPC         164.50        165.80    1.30     0.79         165.80   
2   INDUSINDBK       1,108.00      1,115.00    7.00     0.63       1,115.00   
3         ONGC         133.40        134.10    0.70     0.52         134.10   
4   TATACONSUM         837.45        841.65    4.20     0.50         841.65   
5     HDFCLIFE         573.65        576.40    2.75     0.48         576.40   
6    COALINDIA         231.60        232.70    1.10     0.47         232.70   
7    TATASTEEL         106.90        107.40    0.50     0.47         107.40   
8   BAJFINANCE       7,196.20      7,228.75   32.55     0.45       7,228.75   
9   ADANIPORTS         850.90        854.70    3.80     0.45         854.70   
10        BPCL         324.75        326.00    1.25     0.38         326.00   
11      MARUTI       8,950.05      8,984.30   34.25     0.38       8,984.30   
12  APOLLOHOSP       4,282.55      4,298.90   16.35     0.38       4,298.90   
13         UPL         746.85        749.70    2.85     0.38         749.70   
14     DRREDDY       4,214.25      4,230.00   15.75     0.37       4,230.00   
15       WIPRO         405.50        407.00    1.50     0.37         407.00   
16   KOTAKBANK       1,937.90      1,944.95    7.05     0.36       1,944.95   
17         ITC         328.85        330.00    1.15     0.35         330.00   
18   EICHERMOT       3,400.50      3,412.00   11.50     0.34       3,412.00   
19         M&M       1,320.55      1,325.00    4.45     0.34       1,325.00   
20  BAJAJFINSV      17,376.10     17,425.00   48.90     0.28      17,425.00   
21          LT       1,968.35      1,973.80    5.45     0.28       1,973.80   
22  ULTRACEMCO       6,521.95      6,540.00   18.05     0.28       6,540.00   
23   SUNPHARMA         884.60        887.00    2.40     0.27         887.00   
24   POWERGRID         223.40        224.00    0.60     0.27         224.00   
25    HINDALCO         429.30        430.45    1.15     0.27         430.45   
26    HDFCBANK       1,495.05      1,498.90    3.85     0.26       1,498.90   
27   BRITANNIA       3,662.60      3,672.00    9.40     0.26       3,672.00   
28    AXISBANK         756.10        758.00    1.90     0.25         758.00   
29        HDFC       2,456.25      2,461.00    4.75     0.19       2,461.00   
30       TITAN       2,627.35      2,631.70    4.35     0.17       2,631.70   
31  BAJAJ-AUTO       3,956.65      3,962.00    5.35     0.14       3,962.00   
32    RELIANCE       2,569.80      2,573.00    3.20     0.12       2,573.00   
33         TCS       3,133.40      3,135.50    2.10     0.07       3,135.50   
34    DIVISLAB       3,592.75      3,594.85    2.10     0.06       3,594.85   
35    JSWSTEEL         681.95        682.00    0.05     0.01         682.00   
36   ICICIBANK         882.45        882.50    0.05     0.01         882.50   
37   NESTLEIND      19,259.70     19,260.70    1.00     0.01      19,260.70   
38       TECHM       1,065.05      1,065.05       -        -       1,065.05   
39  HEROMOTOCO       2,842.05      2,842.05       -        -       2,842.05   
40     HCLTECH         936.00        936.00       -        -         936.00   
41        INFY       1,461.30      1,461.30       -        -       1,461.30   
42  BHARTIARTL         740.40        740.40       -        -         740.40   
43    SHREECEM      21,293.65     21,293.00   -0.65    -0.00      21,293.00   
44     SBILIFE       1,293.40      1,293.00   -0.40    -0.03       1,293.00   
45       CIPLA       1,025.65      1,025.00   -0.65    -0.06       1,025.00   
46  ASIANPAINT       3,424.80      3,420.00   -4.80    -0.14       3,420.00   
47        SBIN         538.90        538.00   -0.90    -0.17         538.00   
48  HINDUNILVR       2,600.60      2,591.20   -9.40    -0.36       2,591.20   
49      GRASIM       1,710.75      1,704.00   -6.75    

In [15]:
rows, columns = df1.shape
print('rows',rows)
print('columns',columns)

rows 50
columns 11


In [17]:
## Head prints first n number of rows
print(df1.head(6))

## Head prints first n number of columns
print(df1.tail(9))

    SYMBOL \n PREV. CLOSE \n IEP  PRICE \n CHNG \n %CHNG \n FINAL PRICE \n  \
0  TATAMOTORS         459.00        462.70    3.70     0.81         462.70   
1        NTPC         164.50        165.80    1.30     0.79         165.80   
2  INDUSINDBK       1,108.00      1,115.00    7.00     0.63       1,115.00   
3        ONGC         133.40        134.10    0.70     0.52         134.10   
4  TATACONSUM         837.45        841.65    4.20     0.50         841.65   
5    HDFCLIFE         573.65        576.40    2.75     0.48         576.40   

   FINAL QUANTITY \n         VALUE             FFM CAP  NM 52W H \n  \
0              33180  15,352,386.00  823,121,324,660.88      536.70   
1              76033  12,606,271.40  781,599,773,731.07      166.40   
2               6567   7,322,205.00  721,308,412,308.96    1,242.00   
3              69903   9,373,992.30  520,244,866,284.92      194.95   
4               5315   4,473,369.75  501,639,764,422.39      889.00   
5               2923   1,68

In [19]:
## Slicing a Dataframe
print(df1.iloc[0])
print(df1.iloc[0,0:5])

SYMBOL \n                    TATAMOTORS
PREV. CLOSE \n                   459.00
IEP  PRICE \n                    462.70
CHNG \n                            3.70
%CHNG \n                           0.81
FINAL PRICE \n                   462.70
FINAL QUANTITY \n                 33180
VALUE                     15,352,386.00
FFM CAP              823,121,324,660.88
NM 52W H \n                      536.70
NM 52W L \n                      290.90
Name: 0, dtype: object
SYMBOL \n         TATAMOTORS
PREV. CLOSE \n        459.00
IEP  PRICE \n         462.70
CHNG \n                 3.70
%CHNG \n                0.81
Name: 0, dtype: object


In [20]:
## Descibe
df1.describe()

FINAL QUANTITY \n
count             50.000
mean           14364.900
std            27883.865
min               41.000
25%             1065.750
50%             3886.500
75%            11976.000
max           163501.000

In [5]:
arr1 = np.array([[9.0,8.0,7.0,5.0,9.0],[6.0,5.0,4.0,7.8,6.9],[3,4,6,4,3],[23,6,2,6,64]])
print(arr1)

arr2 = np.array([[9.0,8.0,7.0,5.0,9.0,4.0,3.2,7.9],[6.0,5.0,4.0]], dtype =object)
print(arr2)

[[ 9.   8.   7.   5.   9. ]
 [ 6.   5.   4.   7.8  6.9]
 [ 3.   4.   6.   4.   3. ]
 [23.   6.   2.   6.  64. ]]
[list([9.0, 8.0, 7.0, 5.0, 9.0, 4.0, 3.2, 7.9]) list([6.0, 5.0, 4.0])]


In [8]:
# Get Dimension
print('Dimension of Array 1-',arr1.ndim)
print('Dimension of Array 2-',arr2.ndim)

# Get Shape
print('Shape of Array 1-',arr1.shape)
print('Shape of Array 2-',arr2.shape)

# Get Type
print('Type of Array 1-',arr1.dtype)
print('Type of Array 2-',arr2.dtype)

# Get Size
print('Size ',arr1.itemsize)

# Get number of elements
print('number of elements ',arr1.size)

Dimension of Array 1- 2
Dimension of Array 2- 1
Shape of Array 1- (4, 5)
Shape of Array 2- (2,)
Type of Array 1- float64
Type of Array 2- object
Size  8
number of elements  20


In [10]:
# Get a specific element [r, c]
print(arr1[0, 3])

# Get a specific row 
print(arr1[0, :])

# Get a specific column
print(arr1[:, 2])

# Getting a little more fancy [startindex:endindex:stepsize]
print(arr1[0, 1:-1:2])

5.0
[9. 8. 7. 5. 9.]
[7. 4. 6. 2.]
[8. 5.]


In [12]:
# All 0s matrix
print(np.zeros((6,9)))
print('*'*100)
# All 1s matrix
print(np.ones((4,10,10), dtype='int32'))
print('*'*100)

# Any other number
print(np.full((5,5,5), 99, dtype='int32'))
print('*'*100)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
****************************************************************************************************
[[[1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]]

 [[1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1

In [15]:
# Random decimal numbers
print(np.random.rand(8,8))

# Random Integer values
print(np.random.randint(-100,867, size=(3,3)))

# The identity matrix
print(np.identity(5))

[[3.33607616e-01 5.12764413e-01 5.33565700e-01 7.28685630e-01
  9.35572944e-02 3.77647888e-01 3.16785183e-01 5.10976181e-01]
 [4.94770719e-01 9.70940291e-01 4.53878183e-01 1.90785018e-02
  2.13405263e-01 6.15607692e-04 3.99204778e-02 9.87796719e-02]
 [2.83012600e-01 9.93481168e-01 4.61420318e-01 4.00047708e-02
  3.05501448e-01 7.13905570e-01 3.87573488e-01 4.78194139e-01]
 [7.57172902e-01 3.32050390e-01 2.15146617e-01 8.93280744e-01
  3.51361809e-01 4.67415523e-01 8.74563072e-01 9.78133673e-01]
 [8.44489176e-01 9.32157498e-01 8.40372428e-01 8.82154995e-01
  1.10479156e-01 7.37307029e-02 8.44867099e-01 6.12243497e-01]
 [1.84516345e-01 3.54791251e-01 6.23189875e-01 1.45619847e-01
  7.78769200e-01 5.64054793e-01 7.73164277e-01 9.93926770e-01]
 [8.16780478e-02 1.26434545e-01 5.58178087e-02 5.41804647e-01
  5.46672300e-01 9.65590660e-01 2.88732712e-01 5.43883299e-01]
 [9.55975090e-01 4.66494528e-01 5.39398812e-01 9.65351296e-01
  8.87909230e-01 5.26704432e-01 5.73469397e-01 8.63742032e-01]]

In [4]:
from bs4 import BeautifulSoup

In [5]:
# import requests module
import requests
  
# Making a get request
response = requests.get('http://api.github.com')
  
# print response
print(response)
  
# print url
print(response.url)

<Response [200]>
https://api.github.com/
