In [2]:
import numpy as np


In [3]:
arr1 = np.array([[9.0,8.0,7.0,5.0,9.0],[6.0,5.0,4.0,7.8,6.9]])
print(arr1)

arr2 = np.array([[9.0,8.0,7.0,5.0,9.0,4.0,3.2,7.9],[6.0,5.0,4.0]], dtype =object)
print(arr2)

[[9.  8.  7.  5.  9. ]
 [6.  5.  4.  7.8 6.9]]
[list([9.0, 8.0, 7.0, 5.0, 9.0, 4.0, 3.2, 7.9]) list([6.0, 5.0, 4.0])]


In [5]:
print('Dimension of Array 1-',arr1.ndim)
print('Dimension of Array 2-',arr2.ndim)

print('Shape of Array 1-',arr1.shape)
print('Shape of Array 2-',arr2.shape)


print('Type of Array 1-',arr1.dtype)
print('Type of Array 2-',arr2.dtype)


print('Size: ',arr1.itemsize)


print('Number of elements: ',arr1.size)

Dimension of Array 1- 2
Dimension of Array 2- 1
Shape of Array 1- (2, 5)
Shape of Array 2- (2,)
Type of Array 1- float64
Type of Array 2- object
Size:  8
Number of elements:  10


In [6]:
print(arr1[0, 2])

# Get a specific row 
print(arr1[0, :])

# Get a specific column
print(arr1[:, 2])

# Getting a little more fancy [startindex:endindex:stepsize]
print(arr1[0, 1:-1:2])

7.0
[9. 8. 7. 5. 9.]
[7. 4.]
[8. 5.]


In [7]:
print(np.zeros((2,3)))
print('*'*25)
# All 1s matrix
print(np.ones((4,2,2), dtype='int32'))
print('*'*25)

# Any other number
print(np.full((2,3,2), 99, dtype='int32'))
print('*'*25)

[[0. 0. 0.]
 [0. 0. 0.]]
*************************
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
*************************
[[[99 99]
  [99 99]
  [99 99]]

 [[99 99]
  [99 99]
  [99 99]]]
*************************


In [9]:
print(np.random.rand(4,2))

# Random Integer values
print(np.random.randint(-4,8, size=(3,3)))

# The identity matrix
print(np.identity(5))

[[0.15501174 0.04929949]
 [0.12504213 0.30891565]
 [0.25386764 0.98039511]
 [0.52291185 0.14020221]]
[[ 0  1  7]
 [-1 -1  4]
 [ 5 -1 -3]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
