In [1]:
import numpy as np

In [3]:
arr1 = np.array([[9.0,8.0,7.0,5.0,9.0],[6.0,5.0,4.0,7.8,6.9]])
print(arr1)

arr2 = np.array([[9.0,8.0,7.0,5.0,9.0,4.0,3.2,7.9],[6.0,5.0,4.0]], dtype =object)
print(arr2)

[[9.  8.  7.  5.  9. ]
 [6.  5.  4.  7.8 6.9]]
[list([9.0, 8.0, 7.0, 5.0, 9.0, 4.0, 3.2, 7.9]) list([6.0, 5.0, 4.0])]


In [4]:
print('Dimension of Array 1-',arr1.ndim)
print('Dimension of Array 2-',arr2.ndim)


print('Shape of Array 1-',arr1.shape)
print('Shape of Array 2-',arr2.shape)


print('Type of Array 1-',arr1.dtype)
print('Type of Array 2-',arr2.dtype)


print('Size ',arr1.itemsize)


print('number of elements ',arr1.size)

Dimension of Array 1- 2
Dimension of Array 2- 1
Shape of Array 1- (2, 5)
Shape of Array 2- (2,)
Type of Array 1- float64
Type of Array 2- object
Size  8
number of elements  10


In [6]:
# specific row and column
print(arr1[1, 3])

7.8


In [8]:
print(arr1[1, :])

[6.  5.  4.  7.8 6.9]


In [9]:
print(arr1[:, 3])

[5.  7.8]


In [10]:
print(arr1[1, 1:-1:3])

[5.]


In [12]:
# different arrays
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
print('*'*22)
print(np.ones((3,2,2), dtype='int32'))
print('*'*22)

**********************
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
**********************


In [14]:
print(np.full((3,3,3), 99, dtype='int32'))
print('*'*23)

[[[99 99 99]
  [99 99 99]
  [99 99 99]]

 [[99 99 99]
  [99 99 99]
  [99 99 99]]

 [[99 99 99]
  [99 99 99]
  [99 99 99]]]
***********************


In [15]:
print(np.random.rand(3,4))

[[0.65013524 0.71966009 0.67700313 0.14784392]
 [0.16495721 0.88778528 0.53204924 0.33226218]
 [0.17124555 0.7749636  0.07298903 0.4891834 ]]


In [16]:
print(np.random.randint(-5,9, size=(2,4)))

[[ 7 -2 -2  4]
 [ 3  7  2  2]]


In [17]:
print(np.identity(7))

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
