In [9]:
height = [1.85, 1.75, 1.80, 1.70]
height

weight = [80.4, 85, 70, 74.6]
weight
 
import numpy as np
np_height = np.array(height)
np_height


array([1.85, 1.75, 1.8 , 1.7 ])

In [7]:
np_weight = np.array(weight)
np_weight

array([80.4, 85. , 70. , 74.6])

In [8]:
bmi = np_weight/(np_height**2)
bmi

array([23.49159971, 27.75510204, 21.60493827, 25.81314879])

In [13]:
bmi>25

array([False,  True, False,  True])

In [12]:
bmi[bmi>25]

array([27.75510204, 25.81314879])